set(SRC_FILES
    App.cpp
    AppDebug.cpp
    Bullet.cpp
    ZombieWaveController.cpp
    BasicZombie.cpp
    CardSlot.cpp
    ConeheadZombie.cpp
    CollisionSystem.cpp
    LevelConfig.cpp
    LevelManager.cpp
    LeaderZombie.cpp
    MenuScene.cpp
    CherryBomb.cpp
    PolevaultingZombie.cpp
    Nut.cpp
    Peashooter.cpp
    Sun.cpp
    Sunflower.cpp
    Sunshroom.cpp
    Puffshroom.cpp
    Fumeshroom.cpp
    WaveConfig.cpp
    Zombie.cpp
)

set(INCLUDE_FILES
    App.hpp
    AppDebugConfig.hpp
    Bullet.hpp
    TimerSystem.hpp
    ZombieWaveController.hpp
    BasicZombie.hpp
    CardSlot.hpp
    CollisionSystem.hpp
    ConeheadZombie.hpp
    LevelConfig.hpp
    LevelManager.hpp
    LeaderZombie.hpp
    MenuScene.hpp
    CherryBomb.hpp
    PolevaultingZombie.hpp
    Nut.hpp
    Peashooter.hpp
    Plant.hpp
    Sun.hpp
    Sunflower.hpp
    Sunshroom.hpp
    Puffshroom.hpp
    Fumeshroom.hpp
    WaveConfig.hpp
    Zombie.hpp
    ZombieCollisionBoxHelper.hpp
)

set(TEST_FILES
)
