set(SRC_FILES
    App.cpp
    BasicZombie.cpp
    CardSlot.cpp
    ConeheadZombie.cpp
    LevelConfig.cpp
    LevelManager.cpp
    LeaderZombie.cpp
    MenuScene.cpp
    CherryBomb.cpp
    Nut.cpp
    Peashooter.cpp
    Sun.cpp
    Sunflower.cpp
    Sunshroom.cpp
    WaveConfig.cpp
    Zombie.cpp
)

set(INCLUDE_FILES
    App.hpp
    BasicZombie.hpp
    CardSlot.hpp
    ConeheadZombie.hpp
    LevelConfig.hpp
    LevelManager.hpp
    LeaderZombie.hpp
    MenuScene.hpp
    CherryBomb.hpp
    Nut.hpp
    Peashooter.hpp
    Plant.hpp
    Sun.hpp
    Sunflower.hpp
    Sunshroom.hpp
    WaveConfig.hpp
    Zombie.hpp
)

set(TEST_FILES
)
